repos:
  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
        - "--max-line-length=120"
        - "--ignore=[E203, E266, E501, E722, W503, F403, F401]"
  - repo: https://github.com/PyCQA/autoflake.git
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]
  - repo: https://github.com/pre-commit/mirrors-yapf.git
    rev: v0.32.0
    hooks:
      - id: yapf
        args:
        - "--based_on_style = 'pep8'"
        - "spaces_before_comment = 2"
        - "column_limit = 120"
        - "coalesce_brackets = true"
        - "spaces_around_power_operator = true"
        - "space_between_ending_comma_and_closing_bracket = true"
        - "split_before_closing_bracket = false"
        - "split_before_first_argument = false"
        additional_dependencies: [toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - "--line-length=120"
  - repo: https://github.com/psf/black.git
    rev: 24.4.2
    hooks:
      - id: black
        args:
          - "--line-length=120"
        exclude: ^configs/archive/.*$
  - repo: https://github.com/codespell-project/codespell.git
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: >
            (?x)^(
                .*\.toml
            )$

