# Ultralytics YOLO 🚀, AGPL-3.0 license

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: /root/Projects/datasets/
train: # train images (relative to 'path')  16551 images
    - brain-tumor/train/images/
    - brain-tumor/train/images/

val: # val images (relative to 'path')  4952 images
    - brain-tumor/valid/images/
    - brain-tumor/valid/images/
  
nc: 3

# Classes
names:
  0: negative
  1: positive
